
format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$sudo\
$c\
$conda\
$golang\
$haskell\
$lua\
$python\
$rust\
$character
"""

right_format = """
$docker_context
"""

scan_timeout = 100
add_newline = true
palette = 'catppuccin_mocha'

[os]
disabled = true
format = '[$symbol]($style) '

[username]
style_user = 'white'
style_root = 'red'
format = '[$user]($style)'

[hostname]
ssh_only = true
ssh_symbol = '@'
format = '[$ssh_symbol$hostname]($style) '

[directory]
home_symbol = '~'
read_only = ' 󰌾'
read_only_style = 'red'
truncation_length = 3
truncation_symbol = '…/'
style = 'fg:blue'
format = '[$path]($style)[$read_only]($read_only_style) '

[git_branch]
always_show_remote = false
only_attached = false
symbol = ''
style = 'fg:overlay0'
format = '$symbol[$branch(:$remote_branch)]($style) '

[git_status]
conflicted = '='
stashed = '≡'
deleted = '✘'
renamed = '»'
modified = '!'
staged = '+'
untracked = '?'
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇡${ahead_count}⇣${behind_count}'
up_to_date = ''
style = 'fg:sky'
format = '[$conflicted$untracked$modified$staged$renamed$deleted $ahead_behind $stashed]($style)'

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[git_metrics]
disabled = true
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[cmd_duration]
min_time = 1000
style = "fg:yellow"
format = "[$duration]($style) "

[time]
disabled = true
use_12hr = true
time_format = '%H:%M:%S'
format = '[$time]($style) '

[sudo]
disabled = false
symbol = '⚡'
format = '[$symbol]($style) '

[c]
symbol = ' '
style = 'fg:overlay0'
format = '[$symbol\($name\)]($style) '

[conda]
symbol = ' '
ignore_base = false
style = 'fg:overlay0'
format = '[$symbol\($environment\)]($style) '

[docker_context]
symbol = ' '
only_with_files = false
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_folders = ['.devcontainer']
style = 'fg:overlay0'
format = '[$symbol\($context\)]($style) '

[golang]
symbol = ' '
style = 'fg:overlay0'
format = '[$symbol]($style) '

[haskell]
symbol = ' '
style = 'fg:overlay0'
format = '[$symbol]($style) '

[lua]
symbol = ' '
style = 'fg:overlay0'
format = '[$symbol]($style) '

[python]
python_binary = 'python3'
symbol = ' '
style = 'fg:overlay0'
format = '[$symbol]($style) '

[rust]
symbol = '󱘗 '
style = 'fg:overlay0'
format = '[$symbol]($style) '

[character]
success_symbol = '[❯](green)'
error_symbol = '[❯](red)'
vimcmd_symbol = '[❮](green)'
format = '[$symbol]($style) '

[os.symbols]
Arch = ' '
Debian = ' '
Fedora = ' '
Linux = ' '
Macos = ' '
NixOS = ' '
OpenBSD = '󰈺 '
Pop = ' '
Raspbian = ' '
Ubuntu = ' '
Unknown = ' '
Windows = '󰍲 '

# palettes
[palettes.catppuccin_mocha]
rosewater = '#f5e0dc'
flamingo = '#f2cdcd'
pink = '#f5c2e7'
mauve = '#cba6f7'
red = '#f38ba8'
maroon = '#eba0ac'
peach = '#fab387'
yellow = '#f9e2af'
green = '#a6e3a1'
teal = '#94e2d5'
sky = '#89dceb'
sapphire = '#74c7ec'
blue = '#89b4fa'
lavender = '#b4befe'
text = '#cdd6f4'
subtext1 = '#bac2de'
subtext0 = '#a6adc8'
overlay2 = '#9399b2'
overlay1 = '#7f849c'
overlay0 = '#6c7086'
surface2 = '#585b70'
surface1 = '#45475a'
surface0 = '#313244'
base = '#1e1e2e'
mantle = '#181825'
crust = '#11111b'

[palettes.catppuccin_latte]
rosewater = '#dc8a78'
flamingo = '#dd7878'
pink = '#ea76cb'
mauve = '#8839ef'
red = '#d20f39'
maroon = '#e64553'
peach = '#fe640b'
yellow = '#df8e1d'
green = '#40a02b'
teal = '#179299'
sky = '#04a5e5'
sapphire = '#209fb5'
blue = '#1e66f5'
lavender = '#7287fd'
text = '#4c4f69'
subtext1 = '#5c5f77'
subtext0 = '#6c6f85'
overlay2 = '#7c7f93'
overlay1 = '#8c8fa1'
overlay0 = '#9ca0b0'
surface2 = '#acb0be'
surface1 = '#bcc0cc'
surface0 = '#ccd0da'
base = '#eff1f5'
mantle = '#e6e9ef'
crust = '#dce0e8'
